### PR TITLE
CRS reports for identical bills

### PR DESCRIPTION
**Pull request by ayeshamk**

### CODE REVIEW

**Comment by ayeshamk** [comment]
@aih I do not have CRS data locally to test. If you do, let me know how it works.

**Comment by aih** [comment]
Updates needed:
a) results should be deduplicated, 
b) the bill number should be associated with each CRS report
c) the table in the UI should be updated to show which bill or bills each row is associated with. 

In `get_cosponsors_for_same_bills` we do this by de-duplicating the results, using the bioguide_id. 

A better way to do this is probably with a SQL aggregation query over the CRS reports. I'm not quite sure how to do this with Django models.

Something like:
```sql
SELECT bill.bill_congress_type_number as bill_congress_type_number, crsReportsAgg.title, crsReportsAgg.file, ...
    LEFT JOIN (SELECT bill_congress_type_number, STRING_AGG(crs.ID, '; ') as crsids FROM crsReports 
GROUP BY bill_congress_type_number) crsReportsAgg ON bill.bill_congress_type_number=officersAgg.bill_congress_type_number
```

image

**Comment by aih** [comment]
The bills are associated in a many-to-many relationship with CRS reports, and it should be possible to aggregate using the billnumber:

image

**Comment by aih** [comment]
If it is helpful, I am uploading a .zip of the server database dump (500mb compressed, ~2.5GB json), which includes CRS data. This may not be easy to load to your local environment, depending on postgres versions, etc. When the upload is done, I will send a link to the data.

**Comment by aih** [comment]
See comment on #426

**Comment by aih** [comment]
Without deduplication, this is what a bill CRS context section would look like: all of the combined CRS reports, with no way of telling which report is associated with which bill:

image

**Comment by DanielSchuman** [comment]
That's interesting and I see what you're saying. It's pulling in a ton of
not-that-closely bills and some entirely unrelated.

We will have to (1) limit to only identical bills and title matches; and
(2) deduplicate.

**Comment by amkhan-sudo** [comment]
@aih Added script for CRS report distinction. Would like to merge the PR.

**Comment by aih** [comment]
I'll merge the PR. Note, this does not resolve the issue of showing which bill goes with which crs report.

**Comment by amkhan-sudo** [comment]
@aih Each of the CRS reports is associated with multiple bills. Could you elaborate on what else we need to do? You can create an issue with the details.

**Comment by aih** [comment]
There details are here: https://github.com/aih/FlatGov/issues/426

**Pull request merged**
