### PR TITLE
Feature/committees cosponsors ayesha

### PR DESCRIPTION
**Pull request by ayeshamk**

### CODE REVIEW

**Comment by aih** [comment]
The copy-to-clipboard and download CSV features are great!

Sorting does not appear to be working:
http://localhost:8000/bills/116hr1500
This correctly shows the † and * for sponsor and original cosponsor, respectively, but the top of the list should be: a) the sponsor (Maxine Waters) and any member with rank 1 on a committee of jurisdiction (also Maxine Waters). The others (I think) should be shown in rank order.
image

image

**Comment by ayeshamk** [comment]
Per discussion on Tuesday with Daniel, I implemented the following sorting logic. Find my comment below after the meeting. https://github.com/aih/FlatGov/issues/306#issuecomment-823537535

**Comment by aih** [comment]
From your comment in #306:
>1. Original bill sponsors (D/R) -- #1 and #2 sponsors if they are of different parties, otherwise only the 1st sponsor.

>2. Co-sponsors with rank 1.

In 116hr1500, Maxine Waters is both the `sponsor` and a sponsor with rank 1, so she should be shown first.

**Comment by ayeshamk** [comment]
> From your comment in #306:
> 
> > 1. Original bill sponsors (D/R) -- #1 and #2 sponsors if they are of different parties, otherwise only the 1st sponsor.
> 
> > 1. Co-sponsors with rank 1.
> 
> In 116hr1500, Maxine Waters is both the `sponsor` and a sponsor with rank 1, so she should be shown first.

I picked co-sponsors in the sort, it looks like. I'll add sponsors too.

**Comment by aih** [comment]
And after that, any rank 1 cospsonsors

**Comment by ayeshamk** [comment]
Changed. Working as expected.

image

**Comment by aih** [comment]
Confirmed
image

**Comment by ayeshamk** [comment]
@aih Looks like the merges changed the sorting logic. The orders are different now than what I posted before above for 116hr1500. Here is a screenshot of what we have now on the site:

image

Here is what I originally implemented:

image

The results are the same; it is still showing the expected list. However, the order is different.

**Comment by ayeshamk** [comment]
It is ordered alphabetically now. We do not want the sorting options in the top menu. Daniel asked them to be removed.

image

**Comment by aih** [comment]
@ayeshamk I believe this is a browser cache issue. Check that the version number is `0.3.0`. This version is tied to the git tag; I'll add git tags to future significant updates as well,  so we can confirm that the expected version is in the UI.

image

**Comment by ayeshamk** [comment]
@aih I see the expected behavior from an incognito window.

**Pull request merged**
