### PR TITLE
Feature/commitee 398

### PR DESCRIPTION
**Pull request by ayeshamk**

### CODE REVIEW

**Review by aih — CHANGES_REQUESTED** [review]
This change appears to get all committee documents for the related bills, but does not show the user which bill the committee document is related to.

I think we need a new column in the context tab for the bill number, and each item needs to be associated with the bill that it is associated with. This can be tricky from the db query, since the results do not come back in order; ideally each result will include the billnumber.

**Review by aih — CHANGES_REQUESTED** [review]
The billnumber needs to be converted to the standard form: H.R. 1500 (116). This may require adding the congress to the bill number:
image

**Comment by ayeshamk** [comment]
@aih done

**Review by aih — APPROVED** [review]

**Comment by aih** [comment]
Works:
image

**Pull request merged**
